[project]
name = "url-phishing-classification"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.11.2",
    "pandas>=3.0.6",
    "scikit-learn>=1.9.1",
    "tldextract>=5.3.2",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "pip>=26.2.1",
    "ruff>=0.16.8",
]

[tool.ruff]
line-length = 120
target-version = "py313"

[tool.ruff.lint]
select = ["E", "F", "I", "D"]
